// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAlM86RaI5DwgB0FdPrhLV-3-Z1h6d2R0',
    appId: '1:105319115288:web:ec3ae62bdeba0f88f3716d',
    messagingSenderId: '105319115288',
    projectId: 'flutterjokes',
    authDomain: 'flutterjokes.firebaseapp.com',
    storageBucket: 'flutterjokes.firebasestorage.app',
    measurementId: 'G-EJREFQ64E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGiD1ahDCHnAZx_oq-fVnDqmsXYjoJxHI',
    appId: '1:105319115288:android:94b68026cbcb9ee9f3716d',
    messagingSenderId: '105319115288',
    projectId: 'flutterjokes',
    storageBucket: 'flutterjokes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx8GpZBddtCJW_8nR-tWVaLrU53BtzMpw',
    appId: '1:105319115288:ios:dbcf746660383650f3716d',
    messagingSenderId: '105319115288',
    projectId: 'flutterjokes',
    storageBucket: 'flutterjokes.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx8GpZBddtCJW_8nR-tWVaLrU53BtzMpw',
    appId: '1:105319115288:ios:dbcf746660383650f3716d',
    messagingSenderId: '105319115288',
    projectId: 'flutterjokes',
    storageBucket: 'flutterjokes.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAlM86RaI5DwgB0FdPrhLV-3-Z1h6d2R0',
    appId: '1:105319115288:web:94e69474ececf8def3716d',
    messagingSenderId: '105319115288',
    projectId: 'flutterjokes',
    authDomain: 'flutterjokes.firebaseapp.com',
    storageBucket: 'flutterjokes.firebasestorage.app',
    measurementId: 'G-EM0EQGL7L6',
  );
}
