name: lab1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
